### ISSUE TITLE
Crash on plugin

### ISSUE THREAD

**Issue by atomicbongorg** [pluginever/wp-content-pilot#36]
I was using content pilot. It was working fine. 
But as of yesterday, all the campaigns (YT) got disabled on their own and now wont enable.
I redo the campaign, but it doesnt save or activate.
Please help.

**Comment by sultann** [comment]
@atomicbongorg The campaign automatically get disabled when there is an error. Please check WP Content pilot log why the campaign disabled.

**Comment by atomicbongorg** [comment]
After the last update of the plugin,
All the campaigns lost their active status, frequency, categories etc.


Is there a way to fix this please?

**Comment by sultann** [comment]
@atomicbongorg I am sorry since the last one was a major release of the plugin and a huge code update so there is not actually any way of getting lost settings. 

I will appreciate if you add any feature request here since you are using the plugin for a long time toward making the plugin more useable and robust.

**Comment by atomicbongorg** [comment]
Ok, a good feature would be to allow custom fields in the free version as
others like Content Egg also have it as free.

**Comment by atomicbongorg** [comment]
I fixed all my campaigns that were broken after the last big update.

Now another update 1.05, has once again screwed up all the campaigns. They
don't seem to be working.

I see a message asking me to reactivate the plugin. After doing that, some
campaigns get disabled automatically saying the campaign target has been
reached even though it hasn't.

Please advise.



Thanks,
Ankit

**Comment by sultann** [comment]
Hi @atomicbongorg 
We released another update and set a few notices only.
Few users were complaining that the required tables are not generating when the mysql version is less than 5.7 so the new update just check the table exists or not. If not then ask to reactive so the plugin can try again to create tables.

Another notice added when CRON is not working as the plugin fully dependent on CRON.

I don't know what issue you fixed and how you fixed. If you share more what was the issue and how did you fix then we may take a look.

**Comment by atomicbongorg** [comment]
I redid all my campaigns manually. Didn't really fix anything.

Then another update has deactivated them saying limit is reached, even
though the limit has not been reached.

Cron jobs are active. Content egg is working fine.

**Comment by atomicbongorg** [comment]
Hi

Since the last update, the plugin has become very heavy.
Each campaign is crashing the server when it runs.
This used to not happen earlier.

Please help.

**Comment by atomicbongorg** [comment]
Hi,

It seems that each time a campaign runs, it causes a lot of unmanageable
load on the servers.
This used to not happen earlier. It seems like a serious issue.

Please help.

Thanks,
Ankit.

**Comment by atomicbongorg** [comment]
There is an issue where the YouTube campaigns get all content except the
video itself.
Please help.
